name: Discord Bot CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run linting
      run: npm run lint || true
    
    - name: Run tests
      run: npm test || true
    
    - name: Build
      run: npm run build || true
      
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /var/www/gfort-bot
          git pull
          npm install
          # Ensure all required directories exist
          mkdir -p src/commands
          mkdir -p src/events
          mkdir -p src/utils
          mkdir -p src/handlers
          mkdir -p src/config
          # Ensure proper permissions
          chmod -R 755 .
          # Start or restart the bot
          if pm2 list | grep -q "bot"; then
            pm2 restart bot --update-env
          else
            pm2 start src/index.js --name bot
          fi 